[Ehn]Add rst version to origin command
SuperDARN/rst pull request #433
Opened 2021-06-10 20:12 UTC by mts299

# Scope 

When using `make_fit` and `dattorawacf` it adds the RST version into the `origin.command` at the end. 

**issue**: #422 

## Approval: 1 - simple fix 

## Test

``` bash
make_fit 20180404.0200.12.lyr.rawacf > test.fitacf
dmapdump test.fitacf | grep origin.command | head -n 1
	string	"origin.command" = "make_fit 20180404.0200.12.lyr.rawacf RST Version: 4.5"
```

``` bash
dattorawacf 2005050520d.dat > test.rawacf
dmapdump test.rawacf | grep origin.command | head -n 1
	string	"origin.command" = "dattorawacf 2005050520d.dat RST Version: 4.5"
```

2021-06-11 17:06 UTC, pasha-ponomarenko commented
@mts299, I have downloaded a zipped version of this branch, installed it and found that for some reason it is unstable with respect to `make_fit` and `dattorawacf` functionality. 

Sometimes these commands give this sort of error:
```
`ponomarenko@pasha-linux-main:~/work/origin_add_test> make_fit 20180201.0001.00.hok.rawacf > test_hok.fitacf
*** Error in `make_fit': malloc(): memory corruption (fast): 0x0000000000798a80 ***
Aborted (core dumped)`
```

On other ocassions they seem to work, however, the content of the string is corrupted (see extra stuff between the filename and RST version):

`ponomarenko@pasha-linux-main:~/work/origin_add_test> make_fit 20180201.0001.00.hok.rawacf > test_hok.fitacf
ponomarenko@pasha-linux-main:~/work/origin_add_test> dmapdump test_hok.fitacf | grep origin.command | head -n 1
        string  "origin.command" = "make_fit 20180201.0001.00.hok.rawacf▒Li RST Version: 4.5"`

I reinstalled this branch once more from scratch, but the problem remained.


For comparison, `develop` branch works properly, so it does not look like this is my local machine problem:
```
ponomarenko@pasha-linux-main:~/work/origin_add_test> make_fit 20180201.0001.00.hok.rawacf > test_hok.fitacf
ponomarenko@pasha-linux-main:~/work/origin_add_test> dmapdump test_hok.fitacf | grep origin.command | head -n 1
        string  "origin.command" = "make_fit 20180201.0001.00.hok.rawacf"
ponomarenko@pasha-linux-main:~/work/origin_add_test> dattorawacf 2000050102t.dat > test_t.rawacf
ponomarenko@pasha-linux-main:~/work/origin_add_test> dmapdump test_t.rawacf | grep origin.command | head -n 1
        string  "origin.command" = "dattorawacf 2000050102t.dat"
```

2021-06-14 16:39 UTC, mts299 commented
Thank you for testing @pasha-ponomarenko  I don't get the core dump so going to ask @ecbland to test it as well and then maybe need to do some pair programming to figure this out

2021-06-14 16:42 UTC, mts299 commented
fun I get it when I take `-g` option out which I need to debug

2021-06-14 16:46 UTC, pasha-ponomarenko commented
@mts299, I suspect that something webnt wrong with zipping-unzipping the branch. How do you install yours, directly from github or from a zip file?

2021-06-14 21:17 UTC, ecbland requested changes
I'm still getting core dump after that last commit. Using the same file as @pasha-ponomarenko 
```
make_fit 20180201.0001.00.hok.rawacf > test.fitacf
realloc(): invalid next size
Aborted (core dumped)

make_fit 20180201.0001.00.hok.rawacf > /dev/null
corrupted size vs. prev_size
Aborted (core dumped)
```
Notice the error is different depending on whether I write to an output fitacf file or to `/dev/null`

2021-06-14 21:17 UTC, ecbland commented on codebase/superdarn/src.lib/tk/radar.1.22/src/rprm.c
> +      //fprintf(stderr, "before malloc\n");
```suggestion
```

2021-06-14 21:17 UTC, ecbland commented on codebase/superdarn/src.lib/tk/radar.1.22/src/rprm.c
> +      //fprintf(stderr, "tmp extended\n");
```suggestion
```

2021-06-14 21:17 UTC, ecbland commented on codebase/superdarn/src.lib/tk/radar.1.22/src/rprm.c
> +    strcat(rst_version, " RST Version: ");
Does it make sense to add some kind of delimiter between the command and the RST version number? No strong opinion here.
```suggestion
    strcat(rst_version, " -- RST Version: ");
```

2021-06-15 21:56 UTC, mts299 commented
@ecbland k I will look into it again. Can we not suggest removing the prints until this is working :p I just committed them and then saw it was still core dumping so now I need them again. Normally I will double-check before saying merge haha

2021-06-16 15:56 UTC, mts299 commented
Going to close this PR this is a terrible idea in terms of memory issues. The problem is when origin.command is already set then we add a number of bytes but if we don't have the correct padding this corrupts things and it's a nightmare to deal with. 

I think the more elegant solution is adding an RST.version field as we have for radar and FITACF.

Plus I think that will make it more searchable for users then looking at the origin.command

2021-06-16 15:56 UTC, closed without merging

2021-06-16 16:21 UTC, pasha-ponomarenko commented
Looks like a good riddance!